version: '3'
services:
  web:
    restart: always
    container_name: bookshelf
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000